#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config layout bsp

#padding
yabai -m config top_padding 30
yabai -m config bottom_padding 30
yabai -m config left_padding 30
yabai -m config right_padding 30
yabai -m config window_gap 15

#mouse settings
yabai -m config mouse_follows_focus on 
yabai -m config mouse_modifier alt 
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m mouse_drop_action swap

#Exclude these applications from being managed by yabai
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Caffeinated$" manage=off
yabai -m rule --add app="^Spark$" manage=off


echo "yabai configuration loaded.."
